# Generated by Django 5.0.3 on 2024-06-08 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commentApp2", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment2",
            old_name="content",
            new_name="comment_content",
        ),
    ]
